//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUIApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;root&gt;
        ///	&lt;animation&gt;
        ///		&lt;Name&gt;Float&lt;/Name&gt;
        ///		&lt;Hash&gt;140800401&lt;/Hash&gt;
        ///		&lt;Schedule&gt;1&lt;/Schedule&gt;
        ///		&lt;Animation&gt;1&lt;/Animation&gt;
        ///	&lt;/animation&gt;
        ///	&lt;animation&gt;
        ///		&lt;Name&gt;Bow_Attack_Motorcycle_Draw_Lower_B&lt;/Name&gt;
        ///		&lt;Hash&gt;-846693611&lt;/Hash&gt;
        ///		&lt;Schedule&gt;1&lt;/Schedule&gt;
        ///		&lt;Animation&gt;2&lt;/Animation&gt;
        ///	&lt;/animation&gt;
        ///	&lt;animation&gt;
        ///		&lt;Name&gt;Bow_Attack_Horse_Draw_Lower_B&lt;/Name&gt;
        ///		&lt;Hash&gt;238917901&lt;/Hash&gt;
        ///		&lt;Schedule&gt;1&lt;/Schedule&gt;
        ///		&lt;Animation&gt;3&lt;/Animation&gt;
        ///	&lt;/animation&gt;
        ///	&lt;animation&gt;
        ///		&lt;Name&gt;Bow_Attack_ [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string animationHashes {
            get {
                return ResourceManager.GetString("animationHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;001&quot;: &quot;001&quot;, &quot;002&quot;: &quot;001&quot;, &quot;003&quot;: &quot;001&quot;, &quot;004&quot;: &quot;001&quot;, &quot;015&quot;: &quot;001&quot;, &quot;005&quot;: &quot;005&quot;, &quot;035&quot;: &quot;005&quot;, &quot;039&quot;: &quot;005&quot;, &quot;060&quot;: &quot;005&quot;, &quot;061&quot;: &quot;005&quot;, &quot;006&quot;: &quot;006&quot;, &quot;007&quot;: &quot;006&quot;, &quot;062&quot;: &quot;006&quot;, &quot;063&quot;: &quot;006&quot;, &quot;064&quot;: &quot;006&quot;, &quot;008&quot;: &quot;008&quot;, &quot;040&quot;: &quot;008&quot;, &quot;065&quot;: &quot;008&quot;, &quot;066&quot;: &quot;008&quot;, &quot;067&quot;: &quot;008&quot;, &quot;009&quot;: &quot;009&quot;, &quot;036&quot;: &quot;009&quot;, &quot;071&quot;: &quot;009&quot;, &quot;072&quot;: &quot;009&quot;, &quot;073&quot;: &quot;009&quot;, &quot;012&quot;: &quot;012&quot;, &quot;042&quot;: &quot;012&quot;, &quot;077&quot;: &quot;012&quot;, &quot;078&quot;: &quot;012&quot;, &quot;079&quot;: &quot;012&quot;, ....
        /// </summary>
        internal static string ArmorMapping {
            get {
                return ResourceManager.GetString("ArmorMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check_placeholder {
            get {
                object obj = ResourceManager.GetObject("check_placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Daruk {
            get {
                object obj = ResourceManager.GetObject("Daruk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mipha2 {
            get {
                object obj = ResourceManager.GetObject("Mipha2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;V0&quot;: [&quot;85 db 20 43 &quot;, &quot;Hateno_SheikPad_PowerUp_Activated&quot;], &quot;V1&quot;: [&quot;0d 56 99 d4 &quot;, &quot;Hateno_SheikPad_PowerUp_Eemon&quot;], &quot;V2&quot;: [&quot;0d ba 02 46 &quot;, &quot;Hateno_SheikPad_PowerUp_Explain&quot;], &quot;V3&quot;: [&quot;ba e8 66 5c &quot;, &quot;Hateno_SheikPad_PowerUp_Finish&quot;], &quot;V4&quot;: [&quot;0c 4f 1c d6 &quot;, &quot;Hateno_SheikPad_PowerUp_First&quot;], &quot;V5&quot;: [&quot;63 54 8f e8 &quot;, &quot;Hateno_SheikPad_PowerUp_Guardian&quot;], &quot;V6&quot;: [&quot;ca 59 3b ad &quot;, &quot;Hateno_SheikPad_PowerUp_Huh&quot;], &quot;V7&quot;: [&quot;b6 ab 77 2e &quot;, &quot;Hateno_SheikPad_PowerUp_Ready&quot;], &quot;V8&quot;: [&quot;73 7a dc 41 &quot;, &quot;HigakkareMini_RedDragon [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string QuestFlags {
            get {
                return ResourceManager.GetString("QuestFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;V0&quot;: [&quot;85 db 20 43 &quot;, &quot;Hateno_SheikPad_PowerUp_Activated&quot;], &quot;V1&quot;: [&quot;0d 56 99 d4 &quot;, &quot;Hateno_SheikPad_PowerUp_Eemon&quot;], &quot;V2&quot;: [&quot;0d ba 02 46 &quot;, &quot;Hateno_SheikPad_PowerUp_Explain&quot;], &quot;V3&quot;: [&quot;ba e8 66 5c &quot;, &quot;Hateno_SheikPad_PowerUp_Finish&quot;], &quot;V4&quot;: [&quot;0c 4f 1c d6 &quot;, &quot;Hateno_SheikPad_PowerUp_First&quot;], &quot;V5&quot;: [&quot;63 54 8f e8 &quot;, &quot;Hateno_SheikPad_PowerUp_Guardian&quot;], &quot;V6&quot;: [&quot;ca 59 3b ad &quot;, &quot;Hateno_SheikPad_PowerUp_Huh&quot;], &quot;V7&quot;: [&quot;b6 ab 77 2e &quot;, &quot;Hateno_SheikPad_PowerUp_Ready&quot;], &quot;V8&quot;: [&quot;73 7a dc 41 &quot;, &quot;HigakkareMini_RedDragon [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string QuestFlagsNames {
            get {
                return ResourceManager.GetString("QuestFlagsNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Revali {
            get {
                object obj = ResourceManager.GetObject("Revali", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;serverList&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;127.0.0.0&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;127.0.0.0&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;127.0.0.0&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///&lt;/serverList&gt;.
        /// </summary>
        internal static string serverList {
            get {
                return ResourceManager.GetString("serverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;serverList&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;25.84.121.189&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;25.79.17.118&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///	&lt;server&gt;
        ///		&lt;IP&gt;127.0.0.0&lt;/IP&gt;
        ///		&lt;PASSWORD&gt;&lt;/PASSWORD&gt;
        ///		&lt;PORT&gt;5050&lt;/PORT&gt;
        ///	&lt;/server&gt;
        ///&lt;/serverList&gt;.
        /// </summary>
        internal static string serverLista {
            get {
                return ResourceManager.GetString("serverLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Urbosa {
            get {
                object obj = ResourceManager.GetObject("Urbosa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {&quot;Weapon_Sword_047&quot;: 48, &quot;Weapon_Sword_073&quot;: 40, &quot;Weapon_Sword_024&quot;: 36, &quot;Weapon_Sword_052&quot;: 32, &quot;Weapon_Sword_070&quot;: 30, &quot;Weapon_Sword_003&quot;: 26, &quot;Weapon_Sword_030&quot;: 25, &quot;Weapon_Sword_033&quot;: 24, &quot;Weapon_Sword_025&quot;: 22, &quot;Weapon_Sword_035&quot;: 22, &quot;Weapon_Sword_034&quot;: 20, &quot;Weapon_Sword_029&quot;: 16, &quot;Weapon_Sword_053&quot;: 16, &quot;Weapon_Sword_041&quot;: 15, &quot;Weapon_Sword_027&quot;: 15, &quot;Weapon_Sword_031&quot;: 15, &quot;Weapon_Sword_002&quot;: 14, &quot;Weapon_Sword_021&quot;: 6, &quot;Weapon_Sword_001&quot;: 5, &quot;Weapon_Lsword_047&quot;: 72, &quot;Weapon_Lsword_054&quot;: 60, &quot;Weapon [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string WeaponDamages {
            get {
                return ResourceManager.GetString("WeaponDamages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_placeholder {
            get {
                object obj = ResourceManager.GetObject("x_placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
